In [115]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score,cross_val_predict

In [72]:
data=pd.read_excel('mymachinedata.xlsx')

In [73]:
arr=data.values
x=arr[:,0:8]
y=arr[:,8]


In [74]:
random_state = np.random.RandomState(0)

In [75]:
x

array([[-0.2211281958083716, 6, 890.0, ..., 3, 0, 0],
       [0.03849573892217122, 8, 368.96, ..., 19, 0, 0],
       [-0.2211281958083716, 6, 165.82, ..., 11, 1, 0],
       ...,
       [-0.350940163173643, 4, 345.04, ..., 14, 0, 0],
       [0.5577436083832569, 4, 11.03, ..., 16, 0, 0],
       [-0.7403760652694572, 6, 125.55, ..., 14, 0, 0]], dtype=object)

In [76]:
le = preprocessing.LabelEncoder()

In [77]:
y=le.fit_transform(y)

In [78]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [103]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.4,random_state=random_state)

In [104]:
clf=tree.DecisionTreeClassifier(criterion='gini',min_samples_split=30,class_weight={0:1,1:99},max_features='auto')

In [105]:
clf = clf.fit(x_train,y_train)

In [106]:
y_pred = clf.predict(x_test)

In [107]:
np.unique(y_pred)

array([0, 1], dtype=int64)

In [108]:

accuracy = accuracy_score(y_test,y_pred)

In [109]:
accuracy

0.985375

In [110]:
print(clf.score(x_test,y_test))

0.985375


In [114]:
scores = cross_val_score(clf,x,y,cv=10)
print(scores)

[0.9705   0.9865   0.985    0.9825   0.988    0.987    0.979    0.9865
 0.9915   0.983992]


In [41]:
y_pred.shape

(6600,)

In [33]:
import pickle

In [35]:
data.head()

-0.2211281958083716  6    2000  0  2  18  0.1  0.2  No
0            -0.221128  6  890.00  1  3   3    0    0  No
1             0.038496  8  368.96  1  1  19    0    0  No
2            -0.221128  6  165.82  2  0  11    1    0  No
3            -0.221128  6   96.39  4  2  14    0    0  No
4            -0.740376  2  125.96  1  5  14    0    0  No

In [65]:
x_new1=[[0.3,8,500,5,3,15,1,1]]

In [66]:
y_new=clf.predict_proba(x_new1)[:,1]

In [67]:
print(y_new)

[0.]


In [68]:
x_new2=[[0.3,8,1500,5,3,15,10,0]]

In [69]:
y_new2=clf.predict_proba(x_new2)[:,1]

In [70]:
print(y_new2)

[0.]
